### ISSUE TITLE
Error when try to run drumpad example

### ISSUE THREAD

**Issue by CrayJThiemsert** [adrianstevens/Xamarin-Forms#1]
Hello, I am new Xamarin Dev. I download the Drumpad code. But I found a few errors. Could you please give me a suggestion how to fix it? Thank you.

![image](https://cloud.githubusercontent.com/assets/16893502/22171171/e34d5e34-dfba-11e6-9b11-c0695fbaf17f.png)

**Comment by CrayJThiemsert** [comment]
Continue issue:
I did try to update Xamarin.Forms. After that it allows to build. But it show up the other error when I try to run.

![image](https://cloud.githubusercontent.com/assets/16893502/22171511/3964b1da-dfc2-11e6-895a-a154d93d59a8.png)

![image](https://cloud.githubusercontent.com/assets/16893502/22171529/8e826572-dfc2-11e6-9f89-09fa24968fc5.png)

**Comment by adrianstevens** [comment]
What's the specific error you're seeing now?

A common issue people run into on Windows is the path length issue. Nuget packages like Xamarin.Forms can have very lengthy folder names (take a look at the packages folder in you project).

You may need to move the project to lower/shorter folder location. For example, I have mine in c:\dev\DrumPad (although it shouldn't need to be *that* short.

**Comment by adrianstevens** [comment]
I've updated the DrumPad2 sample code, I'd recommend pulling the latest version - closing issue for now
